is_student(neri_marco).
follows_class(neri_marco,icon).
follows_class(neri_marco,reti).
is_student(azzurri_mattia).
follows_class(azzurri_mattia,reti).
follows_class(azzurri_mattia,mri).
is_student(rossi_mario).
follows_class(rossi_mario,cc).
follows_class(rossi_mario,mri).
is_student(bianchi_luigi).
follows_class(bianchi_luigi,icon).
follows_class(bianchi_luigi,mri).
is_office_room(o101).
is_office_room(o102).
is_office_room(o202).
is_office_room(o201).
is_teacher(paolo_rossi).
teaches_class(paolo_rossi,reti).
office_owner(paolo_rossi,o102).
is_teacher(fabrizio_frizzi).
teaches_class(fabrizio_frizzi,mri).
office_owner(fabrizio_frizzi,o202).
is_teacher(mauro_cioce).
teaches_class(mauro_cioce,cc).
office_owner(mauro_cioce,o101).
is_teacher(massimilino_cavalcanti).
teaches_class(massimilino_cavalcanti,icon).
office_owner(massimilino_cavalcanti,o201).
is_lesson_room(a011).
is_lesson_room(a012).
is_lesson_room(a013).
is_lesson_room(a014).
is_bathroom(b101).
is_bathroom(b102).
is_bathroom(b103).
is_bathroom(b104).
is_study_room(s101).
is_study_room(s102).
is_study_room(s103).
is_study_room(s104).
is_scheduled(icon,a012,get_time(monday,8,30),get_time(monday,10,30)).
is_scheduled(icon,a012,get_time(friday,10,30),get_time(friday,13,30)).
is_scheduled(icon,a012,get_time(wednesday,9,0),get_time(wednesday,11,0)).
is_scheduled(mri,a011,get_time(tuesday,10,30),get_time(tuesday,12,30)).
is_scheduled(mri,a011,get_time(friday,11,30),get_time(friday,13,30)).
is_scheduled(mri,a011,get_time(wednesday,15,0),get_time(wednesday,17,0)).
is_scheduled(cc,a013,get_time(monday,10,30),get_time(monday,12,0)).
is_scheduled(cc,a013,get_time(friday,10,45),get_time(friday,12,45)).
is_scheduled(cc,a013,get_time(thursday,8,0),get_time(thursday,11,0)).
is_scheduled(reti,a014,get_time(monday,11,30),get_time(monday,14,30)).
is_scheduled(reti,a014,get_time(friday,10,30),get_time(friday,13,30)).
is_scheduled(reti,a014,get_time(tuesday,13,0),get_time(tuesday,16,0)).
